In [1]:
import os
import pandas as pd

In [22]:
files

['Download & API Field Descriptions April 2023.pdf',
 'fruits_vegetables.ipynb',
 'Fruits_Vegs_Application',
 'main.ipynb',
 'test.ipynb',
 'vitamins.ipynb',
 'data',
 'recommendation.ipynb',
 'env',
 'readme.txt',
 'webpage_content.html',
 'Prediction_Model.pkl']

In [23]:
import os
data_paths = [os.path.join(os.path.join('..','..','data',i)) for i in os.listdir('..\\..\\data')]

In [24]:
data_paths

['..\\..\\data\\branded_food.csv',
 '..\\..\\data\\food_nutrient.csv',
 '..\\..\\data\\nutrient.csv']

In [30]:
data_paths[1].split('\\')[-1]

'food_nutrient.csv'

In [35]:
data = {}
for i in data_paths:
    print(i)
    data[i.split('\\')[-1]] = pd.read_csv(i)

..\..\data\branded_food.csv

C:\Users\manik\AppData\Local\Temp\ipykernel_6652\3451289035.py:4: DtypeWarning: Columns (2,3,4,6,9,12,17,18,19) have mixed types. Specify dtype option on import or set low_memory=False.
  data[i.split('\\')[-1]] = pd.read_csv(i)

..\..\data\food_nutrient.csv

C:\Users\manik\AppData\Local\Temp\ipykernel_6652\3451289035.py:4: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  data[i.split('\\')[-1]] = pd.read_csv(i)

..\..\data\nutrient.csv

In [40]:
data.keys()

dict_keys(['branded_food.csv', 'food_nutrient.csv', 'nutrient.csv'])

In [8]:
# branded_food
# food_calorie_conversion_factor
# food_nutrient
# food_nutrient_conversion_factor
# food_nutrient_derivation
# food_protein_conversion_factor
# nutrient

In [41]:
nutrient = data['nutrient.csv']
nutrient.info()
nutrient.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 474 entries, 0 to 473
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            474 non-null    int64
 1   name          474 non-null    object
 2   unit_name     474 non-null    object
 3   nutrient_nbr  462 non-null    float64
 4   rank          463 non-null    float64
dtypes: float64(2), int64(1), object(2)
memory usage: 18.6+ KB

     id                               name unit_name  nutrient_nbr   rank
0  2047   Energy (Atwater General Factors)      KCAL         957.0  280.0
1  2048  Energy (Atwater Specific Factors)      KCAL         958.0  290.0
2  1001                             Solids         G         201.0  200.0
3  1002                           Nitrogen         G         202.0  500.0
4  1003                            Protein         G         203.0  600.0

In [42]:
food_nutrient = data['food_nutrient.csv'].iloc[:,:4]
food_nutrient.info()
food_nutrient.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24743726 entries, 0 to 24743725
Data columns (total 4 columns):
 #   Column       Dtype
---  ------       -----
 0   id           int64
 1   fdc_id       int64
 2   nutrient_id  int64
 3   amount       float64
dtypes: float64(1), int64(3)
memory usage: 755.1 MB

         id   fdc_id  nutrient_id  amount
0  13706913  1105904         1003    0.00
1  13706914  1105904         1004   93.33
2  13706915  1105904         1005    0.00
3  13706924  1105904         1110    0.00
4  13706918  1105904         1079    0.00

In [43]:
df1 = food_nutrient.merge(nutrient, left_on = "nutrient_id", right_on = 'id', how = 'inner')
df1.head(2)

,id_x,fdc_id,nutrient_id,amount,id_y,name,unit_name,nutrient_nbr,rank
0,13706913,1105904,1003,0.00,1003,Protein,G,203.0,600.0
1,13706914,1105904,1004,93.33,1004,Total lipid (fat),G,204.0,800.0

In [44]:
branded_food = data['branded_food.csv']
branded_food.info()
branded_food.head(2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1845297 entries, 0 to 1845296
Data columns (total 20 columns):
 #   Column                       Dtype
---  ------                       -----
 0   fdc_id                       int64
 1   brand_owner                  object
 2   brand_name                   object
 3   subbrand_name                object
 4   gtin_upc                     object
 5   ingredients                  object
 6   not_a_significant_source_of  object
 7   serving_size                 float64
 8   serving_size_unit            object
 9   household_serving_fulltext   object
 10  branded_food_category        object
 11  data_source                  object
 12  package_weight               object
 13  modified_date                object
 14  available_date               object
 15  market_country               object
 16  discontinued_date            float64
 17  preparation_state_code       object
 18  trade_channel                object
 19  short_description            object
dtypes: float64(2), int64(1), object(17)
memory usage: 281.6+ MB

,fdc_id,brand_owner,brand_name,subbrand_name,gtin_upc,ingredients,not_a_significant_source_of,serving_size,serving_size_unit,household_serving_fulltext,branded_food_category,data_source,package_weight,modified_date,available_date,market_country,discontinued_date,preparation_state_code,trade_channel,short_description
0,1105904,Richardson Oilseed Products (US) Limited,NaN,NaN,27000612323,Vegetable Oil,NaN,15.0,ml,NaN,Oils Edible,GDSN,NaN,2020-10-02,2020-11-13,United States,NaN,NaN,NaN,NaN
1,1105905,CAMPBELL SOUP COMPANY,NaN,NaN,51000198808,"INGREDIENTS: BEEF STOCK, CONTAINS LESS THAN 2%...",NaN,240.0,ml,NaN,Herbs/Spices/Extracts,GDSN,NaN,2020-09-12,2020-11-13,United States,NaN,NaN,NaN,NaN

In [45]:
branded_food[branded_food.fdc_id == 344646]

,fdc_id,brand_owner,brand_name,subbrand_name,gtin_upc,ingredients,not_a_significant_source_of,serving_size,serving_size_unit,household_serving_fulltext,branded_food_category,data_source,package_weight,modified_date,available_date,market_country,discontinued_date,preparation_state_code,trade_channel,short_description
33062,344646,Kellogg Company US,NaN,NaN,00038000162367,"SUGAR, CORN FLOUR BLEND (WHOLE GRAIN YELLOW CO...",NaN,25.0,g,1 Pouch,Cereals Products - Ready to Eat (Shelf Stable),GDSN,NaN,2016-12-19,2019-04-01,United States,NaN,NaN,NaN,NaN

In [46]:
df1[df1.fdc_id==344646]

,id_x,fdc_id,nutrient_id,amount,id_y,name,unit_name,nutrient_nbr,rank
1164159,6228564,344646,1175,1.79,1175,Vitamin B-6,MG,415.0,6800.0
1164160,6228552,344646,1090,28.00,1090,"Magnesium, Mg",MG,304.0,5500.0
1164161,6228562,344646,1166,1.52,1166,Riboflavin,MG,405.0,6500.0
1164162,6228546,344646,2000,35.90,2000,"Sugars, total including NLEA",G,269.0,1510.0
1164163,6228566,344646,1178,5.40,1178,Vitamin B-12,UG,418.0,7300.0
1164164,6228541,344646,1004,3.70,1004,Total lipid (fat),G,204.0,800.0
1164165,6228563,344646,1167,17.90,1167,Niacin,MG,406.0,6600.0
1164166,6228544,344646,1008,370.00,1008,Energy,KCAL,208.0,300.0
1164167,6228551,344646,1089,16.10,1089,"Iron, Fe",MG,303.0,5400.0
1164168,6228550,344646,1087,16.00,1087,"Calcium, Ca",MG,301.0,5300.0
1164169,6228568,344646,1257,0.00,1257,"Fatty acids, total trans",G,605.0,15400.0
1164170,6228567,344646,1253,0.00,1253,Cholesterol,MG,601.0,15700.0
1164171,6228571,344646,1293,1.00,1293,"Fatty acids, total polyunsaturated",G,646.0,12900.0
1164172,6228557,344646,1104,1786.00,1104,"Vitamin A, IU",IU,318.0,7500.0
1164173,6228558,344646,1110,143.00,1110,"Vitamin D (D2 + D3), International Units",IU,324.0,8650.0
1164174,6228547,344646,1079,10.90,1079,"Fiber, total dietary",G,291.0,1200.0
1164175,6228570,344646,1292,0.60,1292,"Fatty acids, total monounsaturated",G,645.0,11400.0
1164176,6228554,344646,1092,130.00,1092,"Potassium, K",MG,306.0,5700.0
1164177,6228559,344646,1124,0.00,1124,Vitamin E (label entry primarily),IU,340.0,999999.0
1164178,6228555,344646,1093,522.00,1093,"Sodium, Na",MG,307.0,5800.0
1164179,6228569,344646,1258,1.90,1258,"Fatty acids, total saturated",G,606.0,9700.0
1164180,6228545,344646,1051,2.50,1051,Water,G,255.0,100.0
1164181,6228561,344646,1165,1.00,1165,Thiamin,MG,404.0,6400.0
1164182,6228543,344646,1007,0.80,1007,Ash,G,207.0,1000.0
1164183,6228542,344646,1005,87.80,1005,"Carbohydrate, by difference",G,205.0,1110.0
1164184,6228548,344646,1082,2.00,1082,"Fiber, soluble",G,295.0,1240.0
1164185,6228565,344646,1177,357.00,1177,"Folate, total",UG,417.0,6900.0
1164186,6228556,344646,1095,5.40,1095,"Zinc, Zn",MG,309.0,5900.0
1164187,6228553,344646,1091,71.00,1091,"Phosphorus, P",MG,305.0,5600.0
1164188,6228560,344646,1162,54.00,1162,"Vitamin C, total ascorbic acid",MG,401.0,6300.0
1164189,6228549,344646,1084,9.00,1084,"Fiber, insoluble",G,297.0,1260.0
1164190,6228540,344646,1003,5.20,1003,Protein,G,203.0,600.0

In [47]:
df1[df1.fdc_id==344646].pivot(columns = 'name', values = 'amount')

name,Ash,"Calcium, Ca","Carbohydrate, by difference",Cholesterol,Energy,"Fatty acids, total monounsaturated","Fatty acids, total polyunsaturated","Fatty acids, total saturated","Fatty acids, total trans","Fiber, insoluble",...,Thiamin,Total lipid (fat),"Vitamin A, IU",Vitamin B-12,Vitamin B-6,"Vitamin C, total ascorbic acid","Vitamin D (D2 + D3), International Units",Vitamin E (label entry primarily),Water,"Zinc, Zn"
1164159,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.79,NaN,NaN,NaN,NaN,NaN
1164160,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1164161,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1164162,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1164163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,5.4,NaN,NaN,NaN,NaN,NaN,NaN
1164164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1164165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1164166,NaN,NaN,NaN,NaN,370.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1164167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1164168,NaN,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1164169,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1164170,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1164171,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1164172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1786.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1164173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,143.0,NaN,NaN,NaN
1164174,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1164175,NaN,NaN,NaN,NaN,NaN,0.6,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1164176,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1164177,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
1164178,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1164179,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.9,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1164180,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.5,NaN
1164181,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1164182,0.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1164183,NaN,NaN,87.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1164184,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1164185,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1164186,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.4
1164187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1164188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,54.0,NaN,NaN,NaN,NaN
1164189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1164190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
## fetching only fruits and vegetables
df5 = branded_food[~branded_food.branded_food_category.isna()]
df5.info()
df5.head(2)

<class 'pandas.core.frame.DataFrame'>
Index: 1834725 entries, 0 to 1845296
Data columns (total 20 columns):
 #   Column                       Dtype
---  ------                       -----
 0   fdc_id                       int64
 1   brand_owner                  object
 2   brand_name                   object
 3   subbrand_name                object
 4   gtin_upc                     object
 5   ingredients                  object
 6   not_a_significant_source_of  object
 7   serving_size                 float64
 8   serving_size_unit            object
 9   household_serving_fulltext   object
 10  branded_food_category        object
 11  data_source                  object
 12  package_weight               object
 13  modified_date                object
 14  available_date               object
 15  market_country               object
 16  discontinued_date            float64
 17  preparation_state_code       object
 18  trade_channel                object
 19  short_description            object
dtypes: float64(2), int64(1), object(17)
memory usage: 294.0+ MB

,fdc_id,brand_owner,brand_name,subbrand_name,gtin_upc,ingredients,not_a_significant_source_of,serving_size,serving_size_unit,household_serving_fulltext,branded_food_category,data_source,package_weight,modified_date,available_date,market_country,discontinued_date,preparation_state_code,trade_channel,short_description
0,1105904,Richardson Oilseed Products (US) Limited,NaN,NaN,27000612323,Vegetable Oil,NaN,15.0,ml,NaN,Oils Edible,GDSN,NaN,2020-10-02,2020-11-13,United States,NaN,NaN,NaN,NaN
1,1105905,CAMPBELL SOUP COMPANY,NaN,NaN,51000198808,"INGREDIENTS: BEEF STOCK, CONTAINS LESS THAN 2%...",NaN,240.0,ml,NaN,Herbs/Spices/Extracts,GDSN,NaN,2020-09-12,2020-11-13,United States,NaN,NaN,NaN,NaN

In [49]:
fruits_vegs = df5[df5.branded_food_category.str.lower().str.contains('vegetable') | df5.branded_food_category.str.lower().str.contains('fruit')]
fruits_vegs.info()
fruits_vegs.head(2)

<class 'pandas.core.frame.DataFrame'>
Index: 175256 entries, 10 to 1845271
Data columns (total 20 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   fdc_id                       175256 non-null  int64
 1   brand_owner                  174392 non-null  object
 2   brand_name                   124669 non-null  object
 3   subbrand_name                8262 non-null    object
 4   gtin_upc                     175256 non-null  object
 5   ingredients                  173227 non-null  object
 6   not_a_significant_source_of  11122 non-null   object
 7   serving_size                 174754 non-null  float64
 8   serving_size_unit            174015 non-null  object
 9   household_serving_fulltext   73579 non-null   object
 10  branded_food_category        175256 non-null  object
 11  data_source                  175256 non-null  object
 12  package_weight               66734 non-null   object
 13  modified_date                175256 non-null  object
 14  available_date               175256 non-null  object
 15  market_country               175256 non-null  object
 16  discontinued_date            0 non-null       float64
 17  preparation_state_code       3591 non-null    object
 18  trade_channel                1948 non-null    object
 19  short_description            3616 non-null    object
dtypes: float64(2), int64(1), object(17)
memory usage: 28.1+ MB

,fdc_id,brand_owner,brand_name,subbrand_name,gtin_upc,ingredients,not_a_significant_source_of,serving_size,serving_size_unit,household_serving_fulltext,branded_food_category,data_source,package_weight,modified_date,available_date,market_country,discontinued_date,preparation_state_code,trade_channel,short_description
10,1105914,Bush Brothers And Company,NaN,NaN,39400019107,"Prepared Navy Beans, Water, Brown Sugar, Onion...",NaN,130.0,g,NaN,Vegetables Prepared/Processed,GDSN,NaN,2020-09-09,2020-11-13,United States,NaN,NaN,NaN,NaN
11,1105915,Bush Brothers And Company,NaN,NaN,39400017073,"Prepared Organic Chick Peas, Water, Sea Salt.",NaN,130.0,g,NaN,Vegetables Prepared/Processed,GDSN,NaN,2020-09-21,2020-11-13,United States,NaN,NaN,NaN,NaN

In [50]:
related_to_fruits_and_vegetables = [
    'Frozen Fruit & Fruit Juice Concentrates',
    'Canned Fruit',
    'Frozen Vegetables',
    'Fruit & Vegetable Juice, Nectars & Fruit Drinks',
    'Pre-Packaged Fruit & Vegetables',
    'Vegetable and Lentil Mixes',
    'Jam, Jelly & Fruit Spreads',
    'Canned Vegetables',
    'Fruits, Vegetables & Produce',
    'Fruit/Nuts/Seeds Combination',
    'Fruits Unprepared/Unprocessed (Frozen)',
    'Vegetables - Prepared/Processed (Frozen)',
    'Vegetables - Prepared/Processed (Shelf Stable)',
    'Vegetables - Unprepared/Unprocessed (Frozen)',
    'Vegetables - Prepared/Processed',
    'Fruit - Prepared/Processed',
    'Vegetables - Unprepared/Unprocessed (Frozen)',
    'Vegetables - Unprepared/Unprocessed (Shelf Stable)',
    'Vegetables Unprepared/Unprocessed (Shelf Stable)',
    'Fruit',
    'Frozen Fruit',
    'Wrapped Snacks - Fruit Bars',
    'Fresh Fruit and Vegetables',
    'Snack Foods - Dried Fruit',
    'Berries/Small Fruit',
    'Fruits Unprepared/Unprocessed (Shelf Stable)',
    'Fruit/Nuts/Seeds Mixes - Prepared/Processed (Shelf Stable)',
    'Fruit - Prepared/Processed (Frozen)',
    'Fruit Juice - Ready to Drink (Shelf Stable)',
    'Fruit Juice - Not Ready to Drink (Frozen)',
    'Oils Edible - Vegetable or Plant (Shelf Stable)'
]

In [51]:
# def check(x):
#     if x in related_to_fruits_and_vegetables:
#         return True
#     else :return False

In [52]:
fruits_vegs = fruits_vegs[fruits_vegs.branded_food_category.apply(lambda x:True if x in related_to_fruits_and_vegetables else False)]
fruits_vegs.head()

,fdc_id,brand_owner,brand_name,subbrand_name,gtin_upc,ingredients,not_a_significant_source_of,serving_size,serving_size_unit,household_serving_fulltext,branded_food_category,data_source,package_weight,modified_date,available_date,market_country,discontinued_date,preparation_state_code,trade_channel,short_description
176,1106080,The Kroger Co.,NaN,NaN,11110848802,"ORGANIC STRAWBERRIES, ORGANIC PEACHES, ORGANIC...",NaN,140.0,g,NaN,Frozen Fruit & Fruit Juice Concentrates,LI,NaN,2020-04-08,2020-11-13,United States,NaN,NaN,NaN,NaN
191,1106095,"Dole Packaged Foods, LLC",NaN,NaN,38900004095,"PINEAPPLE, WATER, SUGAR, AND CITRIC ACID.",NaN,234.0,g,NaN,Canned Fruit,LI,NaN,2020-09-25,2020-11-13,United States,NaN,NaN,NaN,NaN
192,1106096,Pinnacle Foods Group LLC,NaN,NaN,14500505538,"SUGAR SNAP PEAS, CARROTS, ONIONS, MUSHROOMS.",NaN,96.0,g,NaN,Frozen Vegetables,LI,NaN,2020-04-08,2020-11-13,United States,NaN,NaN,NaN,NaN
238,1106142,"Dole Packaged Foods, LLC",NaN,NaN,71202117629,BLUEBERRIES.,NaN,140.0,g,NaN,Frozen Fruit & Fruit Juice Concentrates,LI,NaN,2020-04-29,2020-11-13,United States,NaN,NaN,NaN,NaN
257,1106161,"Sprout Foods, Inc.",NaN,NaN,818512017085,"ORGANIC PEARS, ORGANIC PEACHES, ORGANIC PUMPKI...",NaN,156.0,g,NaN,"Fruit & Vegetable Juice, Nectars & Fruit Drinks",LI,NaN,2020-04-26,2020-11-13,United States,NaN,NaN,NaN,NaN

In [53]:
df = fruits_vegs.merge(df1,on='fdc_id', how = 'inner')
df.head(2)

,fdc_id,brand_owner,brand_name,subbrand_name,gtin_upc,ingredients,not_a_significant_source_of,serving_size,serving_size_unit,household_serving_fulltext,...,trade_channel,short_description,id_x,nutrient_id,amount,id_y,name,unit_name,nutrient_nbr,rank
0,1106080,The Kroger Co.,NaN,NaN,11110848802,"ORGANIC STRAWBERRIES, ORGANIC PEACHES, ORGANIC...",NaN,140.0,g,NaN,...,NaN,NaN,13415512,1008,64.0,1008,Energy,KCAL,208.0,300.0
1,1106080,The Kroger Co.,NaN,NaN,11110848802,"ORGANIC STRAWBERRIES, ORGANIC PEACHES, ORGANIC...",NaN,140.0,g,NaN,...,NaN,NaN,13415510,1004,0.0,1004,Total lipid (fat),G,204.0,800.0

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1849847 entries, 0 to 1849846
Data columns (total 28 columns):
 #   Column                       Dtype
---  ------                       -----
 0   fdc_id                       int64
 1   brand_owner                  object
 2   brand_name                   object
 3   subbrand_name                object
 4   gtin_upc                     object
 5   ingredients                  object
 6   not_a_significant_source_of  object
 7   serving_size                 float64
 8   serving_size_unit            object
 9   household_serving_fulltext   object
 10  branded_food_category        object
 11  data_source                  object
 12  package_weight               object
 13  modified_date                object
 14  available_date               object
 15  market_country               object
 16  discontinued_date            float64
 17  preparation_state_code       object
 18  trade_channel                object
 19  short_description            object
 20  id_x                         int64
 21  nutrient_id                  int64
 22  amount                       float64
 23  id_y                         int64
 24  name                         object
 25  unit_name                    object
 26  nutrient_nbr                 float64
 27  rank                         float64
dtypes: float64(5), int64(4), object(19)
memory usage: 395.2+ MB

In [55]:
df.isna().sum()

fdc_id                               0
brand_owner                       9098
brand_name                      538329
subbrand_name                  1755148
gtin_upc                             0
ingredients                      23044
not_a_significant_source_of    1776817
serving_size                         0
serving_size_unit                 7111
household_serving_fulltext     1101764
branded_food_category                0
data_source                          0
package_weight                 1138781
modified_date                        0
available_date                       0
market_country                       0
discontinued_date              1849847
preparation_state_code         1848467
trade_channel                  1849227
short_description              1848467
id_x                                 0
nutrient_id                          0
amount                               0
id_y                                 0
name                                 0
unit_name                            0
nutrient_nbr                         0
rank                                13
dtype: int64

In [56]:
dummy = df[['fdc_id', 'nutrient_id', 'branded_food_category', 'ingredients', 'name', 'serving_size', 'amount','unit_name']]
dummy.sample(5)

,fdc_id,nutrient_id,branded_food_category,ingredients,name,serving_size,amount,unit_name
906252,1549057,1093,Frozen Vegetables,MOLOKHIA CHOPPED.,"Sodium, Na",100.0,15.0,MG
658293,1270627,1257,Canned Vegetables,"SPINACH, WATER.","Fatty acids, total trans",121.0,0.0,G
948555,1582801,1104,Frozen Fruit & Fruit Juice Concentrates,ORGANIC BLUEBERRIES.,"Vitamin A, IU",140.0,0.0,IU
1251566,1910462,1253,"Fruit & Vegetable Juice, Nectars & Fruit Drinks","TOMATO JUICE FROM CONCENTRATE (WATER, TOMATO C...",Cholesterol,240.0,0.0,MG
1645445,2372665,1162,Pre-Packaged Fruit & Vegetables,"ROMAINE LETTUCE, RADICCHIO.","Vitamin C, total ascorbic acid",85.0,4.7,MG

In [57]:
dummy[dummy.name == 'Energy'].unit_name.value_counts()

unit_name
KCAL    141755
kJ           4
Name: count, dtype: int64

In [58]:
ids = dummy[dummy.unit_name == 'kJ']['fdc_id']
ids

144828      454151
646442     1259053
909382     1551120
1432022    2062075
Name: fdc_id, dtype: int64

In [59]:
df = dummy[dummy.unit_name != 'kJ']
df.info()
df.head(2)

<class 'pandas.core.frame.DataFrame'>
Index: 1849843 entries, 0 to 1849846
Data columns (total 8 columns):
 #   Column                 Dtype
---  ------                 -----
 0   fdc_id                 int64
 1   nutrient_id            int64
 2   branded_food_category  object
 3   ingredients            object
 4   name                   object
 5   serving_size           float64
 6   amount                 float64
 7   unit_name              object
dtypes: float64(2), int64(2), object(4)
memory usage: 127.0+ MB

,fdc_id,nutrient_id,branded_food_category,ingredients,name,serving_size,amount,unit_name
0,1106080,1008,Frozen Fruit & Fruit Juice Concentrates,"ORGANIC STRAWBERRIES, ORGANIC PEACHES, ORGANIC...",Energy,140.0,64.0,KCAL
1,1106080,1004,Frozen Fruit & Fruit Juice Concentrates,"ORGANIC STRAWBERRIES, ORGANIC PEACHES, ORGANIC...",Total lipid (fat),140.0,0.0,G

In [60]:
final = df[['fdc_id', 'branded_food_category', 'ingredients']]
final.info
final.head()

,fdc_id,branded_food_category,ingredients
0,1106080,Frozen Fruit & Fruit Juice Concentrates,"ORGANIC STRAWBERRIES, ORGANIC PEACHES, ORGANIC..."
1,1106080,Frozen Fruit & Fruit Juice Concentrates,"ORGANIC STRAWBERRIES, ORGANIC PEACHES, ORGANIC..."
2,1106080,Frozen Fruit & Fruit Juice Concentrates,"ORGANIC STRAWBERRIES, ORGANIC PEACHES, ORGANIC..."
3,1106080,Frozen Fruit & Fruit Juice Concentrates,"ORGANIC STRAWBERRIES, ORGANIC PEACHES, ORGANIC..."
4,1106080,Frozen Fruit & Fruit Juice Concentrates,"ORGANIC STRAWBERRIES, ORGANIC PEACHES, ORGANIC..."

In [61]:
piv = df[['fdc_id','name','amount']].pivot(columns = 'name',values = 'amount')
piv.info()
piv.head(2)

<class 'pandas.core.frame.DataFrame'>
Index: 1849843 entries, 0 to 1849846
Data columns (total 59 columns):
 #   Column                                    Dtype
---  ------                                    -----
 0   Ash                                       float64
 1   Biotin                                    float64
 2   Caffeine                                  float64
 3   Calcium, Ca                               float64
 4   Carbohydrate, by difference               float64
 5   Carbohydrate, other                       float64
 6   Carotene, beta                            float64
 7   Chlorine, Cl                              float64
 8   Cholesterol                               float64
 9   Choline, total                            float64
 10  Chromium, Cr                              float64
 11  Copper, Cu                                float64
 12  Energy                                    float64
 13  Epigallocatechin-3-gallate                float64
 14  Fatty acids, total monounsaturated        float64
 15  Fatty acids, total polyunsaturated        float64
 16  Fatty acids, total saturated              float64
 17  Fatty acids, total trans                  float64
 18  Fiber, insoluble                          float64
 19  Fiber, soluble                            float64
 20  Fiber, total dietary                      float64
 21  Folate, DFE                               float64
 22  Folate, total                             float64
 23  Folic acid                                float64
 24  Fructose                                  float64
 25  Glucose                                   float64
 26  Iodine, I                                 float64
 27  Iron, Fe                                  float64
 28  Lutein + zeaxanthin                       float64
 29  Magnesium, Mg                             float64
 30  Manganese, Mn                             float64
 31  Molybdenum, Mo                            float64
 32  Niacin                                    float64
 33  Pantothenic acid                          float64
 34  Phosphorus, P                             float64
 35  Potassium, K                              float64
 36  Protein                                   float64
 37  Riboflavin                                float64
 38  SFA 12:0                                  float64
 39  Selenium, Se                              float64
 40  Sodium, Na                                float64
 41  Sugars, added                             float64
 42  Sugars, total including NLEA              float64
 43  Thiamin                                   float64
 44  Total lipid (fat)                         float64
 45  Total sugar alcohols                      float64
 46  Vitamin A, IU                             float64
 47  Vitamin B-12                              float64
 48  Vitamin B-6                               float64
 49  Vitamin C, total ascorbic acid            float64
 50  Vitamin D (D2 + D3)                       float64
 51  Vitamin D (D2 + D3), International Units  float64
 52  Vitamin D3 (cholecalciferol)              float64
 53  Vitamin E                                 float64
 54  Vitamin E (alpha-tocopherol)              float64
 55  Vitamin K (phylloquinone)                 float64
 56  Water                                     float64
 57  Xylitol                                   float64
 58  Zinc, Zn                                  float64
dtypes: float64(59)
memory usage: 846.8 MB

name,Ash,Biotin,Caffeine,"Calcium, Ca","Carbohydrate, by difference","Carbohydrate, other","Carotene, beta","Chlorine, Cl",Cholesterol,"Choline, total",...,"Vitamin C, total ascorbic acid",Vitamin D (D2 + D3),"Vitamin D (D2 + D3), International Units",Vitamin D3 (cholecalciferol),Vitamin E,Vitamin E (alpha-tocopherol),Vitamin K (phylloquinone),Water,Xylitol,"Zinc, Zn"
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
#combined data
com = pd.concat([final,piv],axis=1)
com.head(2)

,fdc_id,branded_food_category,ingredients,Ash,Biotin,Caffeine,"Calcium, Ca","Carbohydrate, by difference","Carbohydrate, other","Carotene, beta",...,"Vitamin C, total ascorbic acid",Vitamin D (D2 + D3),"Vitamin D (D2 + D3), International Units",Vitamin D3 (cholecalciferol),Vitamin E,Vitamin E (alpha-tocopherol),Vitamin K (phylloquinone),Water,Xylitol,"Zinc, Zn"
0,1106080,Frozen Fruit & Fruit Juice Concentrates,"ORGANIC STRAWBERRIES, ORGANIC PEACHES, ORGANIC...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1106080,Frozen Fruit & Fruit Juice Concentrates,"ORGANIC STRAWBERRIES, ORGANIC PEACHES, ORGANIC...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
com.columns

Index(['fdc_id', 'branded_food_category', 'ingredients', 'Ash', 'Biotin',
       'Caffeine', 'Calcium, Ca', 'Carbohydrate, by difference',
       'Carbohydrate, other', 'Carotene, beta', 'Chlorine, Cl', 'Cholesterol',
       'Choline, total', 'Chromium, Cr', 'Copper, Cu', 'Energy',
       'Epigallocatechin-3-gallate', 'Fatty acids, total monounsaturated',
       'Fatty acids, total polyunsaturated', 'Fatty acids, total saturated',
       'Fatty acids, total trans', 'Fiber, insoluble', 'Fiber, soluble',
       'Fiber, total dietary', 'Folate, DFE', 'Folate, total', 'Folic acid',
       'Fructose', 'Glucose', 'Iodine, I', 'Iron, Fe', 'Lutein + zeaxanthin',
       'Magnesium, Mg', 'Manganese, Mn', 'Molybdenum, Mo', 'Niacin',
       'Pantothenic acid', 'Phosphorus, P', 'Potassium, K', 'Protein',
       'Riboflavin', 'SFA 12:0', 'Selenium, Se', 'Sodium, Na', 'Sugars, added',
       'Sugars, total including NLEA', 'Thiamin', 'Total lipid (fat)',
       'Total sugar alcohols', 'Vitamin A, IU', 'Vitamin B-12', 'Vitamin B-6',
       'Vitamin C, total ascorbic acid', 'Vitamin D (D2 + D3)',
       'Vitamin D (D2 + D3), International Units',
       'Vitamin D3 (cholecalciferol)', 'Vitamin E',
       'Vitamin E (alpha-tocopherol)', 'Vitamin K (phylloquinone)', 'Water',
       'Xylitol', 'Zinc, Zn'],
      dtype='object')

In [64]:
com.iloc[:,:3].head(2)

,fdc_id,branded_food_category,ingredients
0,1106080,Frozen Fruit & Fruit Juice Concentrates,"ORGANIC STRAWBERRIES, ORGANIC PEACHES, ORGANIC..."
1,1106080,Frozen Fruit & Fruit Juice Concentrates,"ORGANIC STRAWBERRIES, ORGANIC PEACHES, ORGANIC..."

In [65]:
res = com.groupby('fdc_id')[com.columns[3:]].mean()
res.reset_index(inplace=True)
res.head(2)

,fdc_id,Ash,Biotin,Caffeine,"Calcium, Ca","Carbohydrate, by difference","Carbohydrate, other","Carotene, beta","Chlorine, Cl",Cholesterol,...,"Vitamin C, total ascorbic acid",Vitamin D (D2 + D3),"Vitamin D (D2 + D3), International Units",Vitamin D3 (cholecalciferol),Vitamin E,Vitamin E (alpha-tocopherol),Vitamin K (phylloquinone),Water,Xylitol,"Zinc, Zn"
0,346432,NaN,NaN,NaN,45.0,15.00,NaN,NaN,NaN,16.0,...,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,348198,NaN,NaN,NaN,31.0,17.69,NaN,NaN,NaN,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
df9 = com.iloc[:,:3].merge(res,on= 'fdc_id')
df9.info()
df9.head(1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1849843 entries, 0 to 1849842
Data columns (total 62 columns):
 #   Column                                    Dtype
---  ------                                    -----
 0   fdc_id                                    int64
 1   branded_food_category                     object
 2   ingredients                               object
 3   Ash                                       float64
 4   Biotin                                    float64
 5   Caffeine                                  float64
 6   Calcium, Ca                               float64
 7   Carbohydrate, by difference               float64
 8   Carbohydrate, other                       float64
 9   Carotene, beta                            float64
 10  Chlorine, Cl                              float64
 11  Cholesterol                               float64
 12  Choline, total                            float64
 13  Chromium, Cr                              float64
 14  Copper, Cu                                float64
 15  Energy                                    float64
 16  Epigallocatechin-3-gallate                float64
 17  Fatty acids, total monounsaturated        float64
 18  Fatty acids, total polyunsaturated        float64
 19  Fatty acids, total saturated              float64
 20  Fatty acids, total trans                  float64
 21  Fiber, insoluble                          float64
 22  Fiber, soluble                            float64
 23  Fiber, total dietary                      float64
 24  Folate, DFE                               float64
 25  Folate, total                             float64
 26  Folic acid                                float64
 27  Fructose                                  float64
 28  Glucose                                   float64
 29  Iodine, I                                 float64
 30  Iron, Fe                                  float64
 31  Lutein + zeaxanthin                       float64
 32  Magnesium, Mg                             float64
 33  Manganese, Mn                             float64
 34  Molybdenum, Mo                            float64
 35  Niacin                                    float64
 36  Pantothenic acid                          float64
 37  Phosphorus, P                             float64
 38  Potassium, K                              float64
 39  Protein                                   float64
 40  Riboflavin                                float64
 41  SFA 12:0                                  float64
 42  Selenium, Se                              float64
 43  Sodium, Na                                float64
 44  Sugars, added                             float64
 45  Sugars, total including NLEA              float64
 46  Thiamin                                   float64
 47  Total lipid (fat)                         float64
 48  Total sugar alcohols                      float64
 49  Vitamin A, IU                             float64
 50  Vitamin B-12                              float64
 51  Vitamin B-6                               float64
 52  Vitamin C, total ascorbic acid            float64
 53  Vitamin D (D2 + D3)                       float64
 54  Vitamin D (D2 + D3), International Units  float64
 55  Vitamin D3 (cholecalciferol)              float64
 56  Vitamin E                                 float64
 57  Vitamin E (alpha-tocopherol)              float64
 58  Vitamin K (phylloquinone)                 float64
 59  Water                                     float64
 60  Xylitol                                   float64
 61  Zinc, Zn                                  float64
dtypes: float64(59), int64(1), object(2)
memory usage: 875.0+ MB

,fdc_id,branded_food_category,ingredients,Ash,Biotin,Caffeine,"Calcium, Ca","Carbohydrate, by difference","Carbohydrate, other","Carotene, beta",...,"Vitamin C, total ascorbic acid",Vitamin D (D2 + D3),"Vitamin D (D2 + D3), International Units",Vitamin D3 (cholecalciferol),Vitamin E,Vitamin E (alpha-tocopherol),Vitamin K (phylloquinone),Water,Xylitol,"Zinc, Zn"
0,1106080,Frozen Fruit & Fruit Juice Concentrates,"ORGANIC STRAWBERRIES, ORGANIC PEACHES, ORGANIC...",NaN,NaN,NaN,21.0,15.0,NaN,NaN,...,32.1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
df9 = df9.drop_duplicates()
df9.info()

<class 'pandas.core.frame.DataFrame'>
Index: 142580 entries, 0 to 1849835
Data columns (total 62 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   fdc_id                                    142580 non-null  int64
 1   branded_food_category                     142580 non-null  object
 2   ingredients                               141063 non-null  object
 3   Ash                                       1 non-null       float64
 4   Biotin                                    112 non-null     float64
 5   Caffeine                                  3 non-null       float64
 6   Calcium, Ca                               114571 non-null  float64
 7   Carbohydrate, by difference               141826 non-null  float64
 8   Carbohydrate, other                       13 non-null      float64
 9   Carotene, beta                            26 non-null      float64
 10  Chlorine, Cl                              3 non-null       float64
 11  Cholesterol                               107561 non-null  float64
 12  Choline, total                            13 non-null      float64
 13  Chromium, Cr                              27 non-null      float64
 14  Copper, Cu                                892 non-null     float64
 15  Energy                                    141753 non-null  float64
 16  Epigallocatechin-3-gallate                3 non-null       float64
 17  Fatty acids, total monounsaturated        2542 non-null    float64
 18  Fatty acids, total polyunsaturated        2549 non-null    float64
 19  Fatty acids, total saturated              108567 non-null  float64
 20  Fatty acids, total trans                  110003 non-null  float64
 21  Fiber, insoluble                          49 non-null      float64
 22  Fiber, soluble                            50 non-null      float64
 23  Fiber, total dietary                      115197 non-null  float64
 24  Folate, DFE                               10 non-null      float64
 25  Folate, total                             3458 non-null    float64
 26  Folic acid                                226 non-null     float64
 27  Fructose                                  4 non-null       float64
 28  Glucose                                   1 non-null       float64
 29  Iodine, I                                 141 non-null     float64
 30  Iron, Fe                                  111652 non-null  float64
 31  Lutein + zeaxanthin                       26 non-null      float64
 32  Magnesium, Mg                             4404 non-null    float64
 33  Manganese, Mn                             1542 non-null    float64
 34  Molybdenum, Mo                            22 non-null      float64
 35  Niacin                                    3541 non-null    float64
 36  Pantothenic acid                          1095 non-null    float64
 37  Phosphorus, P                             1797 non-null    float64
 38  Potassium, K                              78707 non-null   float64
 39  Protein                                   141778 non-null  float64
 40  Riboflavin                                2816 non-null    float64
 41  SFA 12:0                                  5 non-null       float64
 42  Selenium, Se                              205 non-null     float64
 43  Sodium, Na                                139807 non-null  float64
 44  Sugars, added                             24754 non-null   float64
 45  Sugars, total including NLEA              140850 non-null  float64
 46  Thiamin                                   4538 non-null    float64
 47  Total lipid (fat)                         136349 non-null  float64
 48  Total sugar alcohols                      286 non-null     float64
 49  Vitamin A, IU                             58107 non-null   float64
 50  Vitamin B-12                              840 non-null     float64
 51  Vitamin B-6                               4553 non-null    float64
 52  Vitamin C, total ascorbic acid            85976 non-null   float64
 53  Vitamin D (D2 + D3)                       6 non-null       float64
 54  Vitamin D (D2 + D3), International Units  51963 non-null   float64
 55  Vitamin D3 (cholecalciferol)              1 non-null       float64
 56  Vitamin E                                 359 non-null     float64
 57  Vitamin E (alpha-tocopherol)              297 non-null     float64
 58  Vitamin K (phylloquinone)                 2829 non-null    float64
 59  Water                                     4 non-null       float64
 60  Xylitol                                   13 non-null      float64
 61  Zinc, Zn                                  1118 non-null    float64
dtypes: float64(59), int64(1), object(2)
memory usage: 68.5+ MB

In [68]:
df9.isna().sum()

fdc_id                               0
branded_food_category                0
ingredients                       1517
Ash                             142579
Biotin                          142468
                                 ...
Vitamin E (alpha-tocopherol)    142283
Vitamin K (phylloquinone)       139751
Water                           142576
Xylitol                         142567
Zinc, Zn                        141462
Length: 62, dtype: int64

In [69]:
dummy = df9.copy()

In [35]:
count = 0
for i in dummy.columns:
    if dummy[i].isna().sum()>100000:
        dummy.drop(i,axis='columns', inplace=True)
        count+=1
print(count)

43

In [36]:
dummy

,fdc_id,branded_food_category,ingredients,"Calcium, Ca","Carbohydrate, by difference",Cholesterol,Energy,"Fatty acids, total saturated","Fatty acids, total trans","Fiber, total dietary","Iron, Fe","Potassium, K",Protein,"Sodium, Na","Sugars, total including NLEA",Total lipid (fat),"Vitamin A, IU","Vitamin C, total ascorbic acid","Vitamin D (D2 + D3), International Units"
0,1106080,Frozen Fruit & Fruit Juice Concentrates,"ORGANIC STRAWBERRIES, ORGANIC PEACHES, ORGANIC...",21.0,15.00,0.0,64.0,0.0,0.0,1.4,28.57,171.0,0.71,0.0,12.14,0.00,NaN,32.1,0.0
15,1106095,Canned Fruit,"PINEAPPLE, WATER, SUGAR, AND CITRIC ACID.",0.0,20.94,0.0,85.0,0.0,0.0,0.9,0.15,NaN,0.43,0.0,20.09,0.00,NaN,9.0,0.0
30,1106096,Frozen Vegetables,"SUGAR SNAP PEAS, CARROTS, ONIONS, MUSHROOMS.",42.0,8.33,0.0,42.0,0.0,0.0,2.1,0.42,156.0,1.04,26.0,4.17,0.00,NaN,NaN,0.0
44,1106142,Frozen Fruit & Fruit Juice Concentrates,BLUEBERRIES.,0.0,12.14,0.0,57.0,0.0,0.0,2.9,0.00,54.0,0.71,0.0,8.57,0.71,0.0,2.6,NaN
59,1106161,"Fruit & Vegetable Juice, Nectars & Fruit Drinks","ORGANIC PEARS, ORGANIC PEACHES, ORGANIC PUMPKI...",38.0,15.38,0.0,83.0,0.0,0.0,2.6,0.46,173.0,2.56,3.0,8.97,1.28,321.0,7.7,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1849775,2554819,Canned Vegetables,"GREEN CABBAGE, FILTERED WATER SEA SALT, CARAWA...",33.0,1.67,0.0,17.0,0.0,0.0,1.7,0.00,117.0,1.67,783.0,0.00,0.00,NaN,NaN,0.0
1849789,2554823,"Jam, Jelly & Fruit Spreads","PURIFIED WATER, ERYTHRITOL, PHYTOCOLLAGEN, STR...",16.0,10.67,0.0,7.0,0.0,0.0,0.7,0.13,47.0,0.00,59.0,0.00,0.00,4800.0,240.0,0.0
1849807,2554871,Frozen Vegetables,ORGANIC GREEN PEAS,24.0,14.12,0.0,82.0,0.0,0.0,4.7,1.18,111.0,4.71,71.0,4.71,0.00,NaN,NaN,0.0
1849821,2554878,Pre-Packaged Fruit & Vegetables,"CANTALOUPE, HONEYDEW, PINEAPPLE, MANGO, STRAWB...",14.0,12.14,0.0,50.0,0.0,0.0,1.4,0.26,150.0,0.71,7.0,10.00,0.00,NaN,NaN,0.0
1849835,2554889,"Fruit & Vegetable Juice, Nectars & Fruit Drinks","APPLE JUICE FROM CONCENTRATE (WATER, JUICE CON...",NaN,12.00,NaN,48.0,NaN,NaN,NaN,NaN,120.0,0.00,8.0,11.20,0.00,NaN,43.2,NaN

<h1> Model Building

In [37]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,LogisticRegression,ridge_regression
from sklearn.metrics import r2_score
from sklearn.compose import ColumnTransformer

In [38]:
dummy.head(1)

,fdc_id,branded_food_category,ingredients,"Calcium, Ca","Carbohydrate, by difference",Cholesterol,Energy,"Fatty acids, total saturated","Fatty acids, total trans","Fiber, total dietary","Iron, Fe","Potassium, K",Protein,"Sodium, Na","Sugars, total including NLEA",Total lipid (fat),"Vitamin A, IU","Vitamin C, total ascorbic acid","Vitamin D (D2 + D3), International Units"
0,1106080,Frozen Fruit & Fruit Juice Concentrates,"ORGANIC STRAWBERRIES, ORGANIC PEACHES, ORGANIC...",21.0,15.0,0.0,64.0,0.0,0.0,1.4,28.57,171.0,0.71,0.0,12.14,0.0,NaN,32.1,0.0

In [39]:
x = dummy.drop(["Energy",'branded_food_category','ingredients'], axis = 'columns').set_index('fdc_id')
y = dummy[['Energy','fdc_id']].set_index('fdc_id')

x = x.fillna(0)
y = y.fillna(0)

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

lr = LinearRegression()
lr.fit(x_train,y_train)

pred = lr.predict(x_test)

r2_score(y_test,pred)

0.9908543732580669

In [40]:
x.info()
x.head(1)

<class 'pandas.core.frame.DataFrame'>
Index: 142580 entries, 1106080 to 2554889
Data columns (total 15 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   Calcium, Ca                               142580 non-null  float64
 1   Carbohydrate, by difference               142580 non-null  float64
 2   Cholesterol                               142580 non-null  float64
 3   Fatty acids, total saturated              142580 non-null  float64
 4   Fatty acids, total trans                  142580 non-null  float64
 5   Fiber, total dietary                      142580 non-null  float64
 6   Iron, Fe                                  142580 non-null  float64
 7   Potassium, K                              142580 non-null  float64
 8   Protein                                   142580 non-null  float64
 9   Sodium, Na                                142580 non-null  float64
 10  Sugars, total including NLEA              142580 non-null  float64
 11  Total lipid (fat)                         142580 non-null  float64
 12  Vitamin A, IU                             142580 non-null  float64
 13  Vitamin C, total ascorbic acid            142580 non-null  float64
 14  Vitamin D (D2 + D3), International Units  142580 non-null  float64
dtypes: float64(15)
memory usage: 17.4 MB

,"Calcium, Ca","Carbohydrate, by difference",Cholesterol,"Fatty acids, total saturated","Fatty acids, total trans","Fiber, total dietary","Iron, Fe","Potassium, K",Protein,"Sodium, Na","Sugars, total including NLEA",Total lipid (fat),"Vitamin A, IU","Vitamin C, total ascorbic acid","Vitamin D (D2 + D3), International Units"
fdc_id,,,,,,,,,,,,,,,
1106080,21.0,15.0,0.0,0.0,0.0,1.4,28.57,171.0,0.71,0.0,12.14,0.0,0.0,32.1,0.0

In [41]:
import pickle
with open('model_1.pkl', 'wb') as model_file:
    pickle.dump(lr, model_file)

<h1> Model with ingreadients

In [42]:
dummy.sample()

,fdc_id,branded_food_category,ingredients,"Calcium, Ca","Carbohydrate, by difference",Cholesterol,Energy,"Fatty acids, total saturated","Fatty acids, total trans","Fiber, total dietary","Iron, Fe","Potassium, K",Protein,"Sodium, Na","Sugars, total including NLEA",Total lipid (fat),"Vitamin A, IU","Vitamin C, total ascorbic acid","Vitamin D (D2 + D3), International Units"
1077191,1692861,Frozen Fruit & Fruit Juice Concentrates,"HIGH FRUCTOSE CORN SYRUP, WATER, CONCENTRATED ...",NaN,43.33,NaN,183.0,0.0,NaN,NaN,NaN,NaN,1.67,0.0,31.67,0.0,NaN,41.7,NaN

In [43]:
lol = dummy.drop(['branded_food_category'],axis='columns').set_index('fdc_id')
lol = lol[lol.ingredients.str.contains('[a-zA-Z]', na=False)]

In [44]:
from category_encoders import CountEncoder

In [45]:
import category_encoders as ce

In [46]:
lol.shape

(141063, 17)

In [47]:
count_enc = CountEncoder()
ingredients = count_enc.fit_transform(lol['ingredients'])

In [48]:
binary_enc = ce.BinaryEncoder()
ingredients = binary_enc.fit_transform(lol['ingredients'])

In [49]:
with open('binary_enc.pkl', 'wb') as model_file:
    pickle.dump(binary_enc, model_file)

In [50]:
final_df = pd.concat([lol,ingredients],axis=1)
final_df.head()
final_df.fillna(0,inplace=True)
df_10 = final_df.drop('ingredients',axis='columns')
df_10

,"Calcium, Ca","Carbohydrate, by difference",Cholesterol,Energy,"Fatty acids, total saturated","Fatty acids, total trans","Fiber, total dietary","Iron, Fe","Potassium, K",Protein,...,ingredients_5,ingredients_6,ingredients_7,ingredients_8,ingredients_9,ingredients_10,ingredients_11,ingredients_12,ingredients_13,ingredients_14
fdc_id,,,,,,,,,,,,,,,,,,,,,
1106080,21.0,15.00,0.0,64.0,0.0,0.0,1.4,28.57,171.0,0.71,...,0,0,0,0,0,0,0,0,0,1
1106095,0.0,20.94,0.0,85.0,0.0,0.0,0.9,0.15,0.0,0.43,...,0,0,0,0,0,0,0,0,1,0
1106096,42.0,8.33,0.0,42.0,0.0,0.0,2.1,0.42,156.0,1.04,...,0,0,0,0,0,0,0,0,1,1
1106142,0.0,12.14,0.0,57.0,0.0,0.0,2.9,0.00,54.0,0.71,...,0,0,0,0,0,0,0,1,0,0
1106161,38.0,15.38,0.0,83.0,0.0,0.0,2.6,0.46,173.0,2.56,...,0,0,0,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2554819,33.0,1.67,0.0,17.0,0.0,0.0,1.7,0.00,117.0,1.67,...,0,0,0,1,1,0,1,1,1,0
2554823,16.0,10.67,0.0,7.0,0.0,0.0,0.7,0.13,47.0,0.00,...,0,0,0,1,1,0,1,1,1,1
2554871,24.0,14.12,0.0,82.0,0.0,0.0,4.7,1.18,111.0,4.71,...,0,1,0,1,0,1,1,1,1,0
2554878,14.0,12.14,0.0,50.0,0.0,0.0,1.4,0.26,150.0,0.71,...,0,0,0,1,1,1,0,0,0,0
2554889,0.0,12.00,0.0,48.0,0.0,0.0,0.0,0.00,120.0,0.00,...,1,0,0,0,0,0,0,0,0,1

In [51]:
# lol = pd.get_dummies(lol,drop_first=True,sparse=False,columns=['ingredients'])
# lol.head(2)

In [52]:
x_dummy = df_10.drop(['Energy'],axis= 'columns')
y_dummy = df_10[['Energy']]

In [53]:
from sklearn.decomposition import PCA
pca = PCA(16)
x_dummy = pca.fit_transform(x_dummy)

In [54]:
with open('pca.pkl', 'wb') as model_file:
    pickle.dump(pca, model_file)

In [55]:
x_dummy_train,x_dummy_test,y_dummy_train,y_dummy_test = train_test_split(x_dummy,y_dummy,test_size=0.2,random_state=42)

In [56]:
x_dummy_train

array([[-3.41143232e+03, -2.83264292e+01, -2.38475273e+02, ...,
        -1.44592532e-01, -9.61520979e-01, -1.26685832e-01],
       [-3.41133579e+03, -2.85780236e+01,  3.27536461e+02, ...,
        -1.01631823e+00,  2.18548300e-01,  1.08186429e-01],
       [-3.41143293e+03, -2.83247021e+01, -2.38588632e+02, ...,
        -9.20234963e-02,  7.52222041e-01,  8.87229925e-01],
       ...,
       [-3.41142759e+03, -2.83398933e+01, -1.55471324e+02, ...,
        -4.29734126e-02, -4.85071780e-01,  8.22853307e-01],
       [-3.41141940e+03, -2.83638174e+01, -2.64113688e+01, ...,
        -2.15129418e-02, -3.59948146e-01,  4.28107370e-01],
       [-3.41142246e+03, -2.83543142e+01, -9.73172900e+01, ...,
        -1.93232189e-02,  7.14462781e-01,  4.29915469e-01]])

In [57]:
y_dummy_train

         Energy
fdc_id
2060011   250.0
1343679   353.0
2271786     4.0
701440     53.0
1350694    48.0
...         ...
2066949    50.0
2202450    75.0
1981531    17.0
2420556    29.0
2270482    23.0

[112850 rows x 1 columns]

In [58]:
lr = LinearRegression()
lr.fit(x_dummy_train,y_dummy_train)

LinearRegression()

In [59]:
with open('model_2.pkl', 'wb') as model_file:
    pickle.dump(lr, model_file)

In [60]:
pred_dummy = lr.predict(x_dummy_test)

In [61]:
r2_score(y_dummy_test,pred_dummy)

0.9906722341616759

In [62]:
test = final_df.sample().iloc[:,:17]
test = pd.concat([test.drop(['ingredients','Energy'],axis = 'columns'),binary_enc.transform(test.ingredients)],
                 axis=1)
ind = test.index[0]
test

,"Calcium, Ca","Carbohydrate, by difference",Cholesterol,"Fatty acids, total saturated","Fatty acids, total trans","Fiber, total dietary","Iron, Fe","Potassium, K",Protein,"Sodium, Na",...,ingredients_5,ingredients_6,ingredients_7,ingredients_8,ingredients_9,ingredients_10,ingredients_11,ingredients_12,ingredients_13,ingredients_14
fdc_id,,,,,,,,,,,,,,,,,,,,,
591904,0.0,50.0,0.0,0.0,0.0,5.6,0.0,0.0,0.0,28.0,...,1,0,0,1,1,0,0,1,1,0

In [63]:
test = pca.transform(test)
lr.predict(test)

array([[178.07457778]])

In [64]:
dummy[dummy.fdc_id == ind]

,fdc_id,branded_food_category,ingredients,"Calcium, Ca","Carbohydrate, by difference",Cholesterol,Energy,"Fatty acids, total saturated","Fatty acids, total trans","Fiber, total dietary","Iron, Fe","Potassium, K",Protein,"Sodium, Na","Sugars, total including NLEA",Total lipid (fat),"Vitamin A, IU","Vitamin C, total ascorbic acid","Vitamin D (D2 + D3), International Units"
307901,591904,"Jam, Jelly & Fruit Spreads","STRAWBERRIES, MAPLE SYRUP, STRAWBERRY JUICE CO...",NaN,50.0,NaN,278.0,NaN,NaN,5.6,NaN,NaN,0.0,28.0,50.0,0.0,NaN,NaN,NaN

In [65]:
branded_food[branded_food.fdc_id == ind]

,fdc_id,brand_owner,brand_name,subbrand_name,gtin_upc,ingredients,not_a_significant_source_of,serving_size,serving_size_unit,household_serving_fulltext,branded_food_category,data_source,package_weight,modified_date,available_date,market_country,discontinued_date,preparation_state_code,trade_channel,short_description
278016,591904,"B&G Foods North America, Inc.",NaN,NaN,72400000409,"STRAWBERRIES, MAPLE SYRUP, STRAWBERRY JUICE CO...",NaN,18.0,g,1 Tbsp,"Jam, Jelly & Fruit Spreads",LI,NaN,2018-08-11,2019-04-01,United States,NaN,NaN,NaN,NaN

In [66]:
dummy.head()

,fdc_id,branded_food_category,ingredients,"Calcium, Ca","Carbohydrate, by difference",Cholesterol,Energy,"Fatty acids, total saturated","Fatty acids, total trans","Fiber, total dietary","Iron, Fe","Potassium, K",Protein,"Sodium, Na","Sugars, total including NLEA",Total lipid (fat),"Vitamin A, IU","Vitamin C, total ascorbic acid","Vitamin D (D2 + D3), International Units"
0,1106080,Frozen Fruit & Fruit Juice Concentrates,"ORGANIC STRAWBERRIES, ORGANIC PEACHES, ORGANIC...",21.0,15.00,0.0,64.0,0.0,0.0,1.4,28.57,171.0,0.71,0.0,12.14,0.00,NaN,32.1,0.0
15,1106095,Canned Fruit,"PINEAPPLE, WATER, SUGAR, AND CITRIC ACID.",0.0,20.94,0.0,85.0,0.0,0.0,0.9,0.15,NaN,0.43,0.0,20.09,0.00,NaN,9.0,0.0
30,1106096,Frozen Vegetables,"SUGAR SNAP PEAS, CARROTS, ONIONS, MUSHROOMS.",42.0,8.33,0.0,42.0,0.0,0.0,2.1,0.42,156.0,1.04,26.0,4.17,0.00,NaN,NaN,0.0
44,1106142,Frozen Fruit & Fruit Juice Concentrates,BLUEBERRIES.,0.0,12.14,0.0,57.0,0.0,0.0,2.9,0.00,54.0,0.71,0.0,8.57,0.71,0.0,2.6,NaN
59,1106161,"Fruit & Vegetable Juice, Nectars & Fruit Drinks","ORGANIC PEARS, ORGANIC PEACHES, ORGANIC PUMPKI...",38.0,15.38,0.0,83.0,0.0,0.0,2.6,0.46,173.0,2.56,3.0,8.97,1.28,321.0,7.7,NaN

<h1>Building Recommendation system

In [67]:
rec = dummy.copy()
rec.sample()

,fdc_id,branded_food_category,ingredients,"Calcium, Ca","Carbohydrate, by difference",Cholesterol,Energy,"Fatty acids, total saturated","Fatty acids, total trans","Fiber, total dietary","Iron, Fe","Potassium, K",Protein,"Sodium, Na","Sugars, total including NLEA",Total lipid (fat),"Vitamin A, IU","Vitamin C, total ascorbic acid","Vitamin D (D2 + D3), International Units"
1396640,2026205,Canned Fruit,"FRUIT (PEACHES, PEARS, CHERRIES [CHERRIES, CAR...",0.0,15.93,0.0,62.0,0.0,0.0,0.9,0.0,62.0,0.0,4.0,14.16,0.0,88.0,10.6,NaN

In [68]:
rec.iloc[:,3:]

,"Calcium, Ca","Carbohydrate, by difference",Cholesterol,Energy,"Fatty acids, total saturated","Fatty acids, total trans","Fiber, total dietary","Iron, Fe","Potassium, K",Protein,"Sodium, Na","Sugars, total including NLEA",Total lipid (fat),"Vitamin A, IU","Vitamin C, total ascorbic acid","Vitamin D (D2 + D3), International Units"
0,21.0,15.00,0.0,64.0,0.0,0.0,1.4,28.57,171.0,0.71,0.0,12.14,0.00,NaN,32.1,0.0
15,0.0,20.94,0.0,85.0,0.0,0.0,0.9,0.15,NaN,0.43,0.0,20.09,0.00,NaN,9.0,0.0
30,42.0,8.33,0.0,42.0,0.0,0.0,2.1,0.42,156.0,1.04,26.0,4.17,0.00,NaN,NaN,0.0
44,0.0,12.14,0.0,57.0,0.0,0.0,2.9,0.00,54.0,0.71,0.0,8.57,0.71,0.0,2.6,NaN
59,38.0,15.38,0.0,83.0,0.0,0.0,2.6,0.46,173.0,2.56,3.0,8.97,1.28,321.0,7.7,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1849775,33.0,1.67,0.0,17.0,0.0,0.0,1.7,0.00,117.0,1.67,783.0,0.00,0.00,NaN,NaN,0.0
1849789,16.0,10.67,0.0,7.0,0.0,0.0,0.7,0.13,47.0,0.00,59.0,0.00,0.00,4800.0,240.0,0.0
1849807,24.0,14.12,0.0,82.0,0.0,0.0,4.7,1.18,111.0,4.71,71.0,4.71,0.00,NaN,NaN,0.0
1849821,14.0,12.14,0.0,50.0,0.0,0.0,1.4,0.26,150.0,0.71,7.0,10.00,0.00,NaN,NaN,0.0
1849835,NaN,12.00,NaN,48.0,NaN,NaN,NaN,NaN,120.0,0.00,8.0,11.20,0.00,NaN,43.2,NaN

In [69]:
rec['combined_text'] = rec['branded_food_category'].astype(str) + ' ' + rec['ingredients'].astype(str)
rec['combined_features'] = rec['branded_food_category'].astype(str) + ' ' + rec['ingredients'].astype(str) + ' ' + rec.iloc[:,3:].astype(str).agg(' '.join, axis=1)

In [70]:
rec_features= rec[['ingredients','combined_features']].drop_duplicates()
rec_features.head()

,ingredients,combined_features
0,"ORGANIC STRAWBERRIES, ORGANIC PEACHES, ORGANIC...",Frozen Fruit & Fruit Juice Concentrates ORGANI...
15,"PINEAPPLE, WATER, SUGAR, AND CITRIC ACID.","Canned Fruit PINEAPPLE, WATER, SUGAR, AND CITR..."
30,"SUGAR SNAP PEAS, CARROTS, ONIONS, MUSHROOMS.","Frozen Vegetables SUGAR SNAP PEAS, CARROTS, ON..."
44,BLUEBERRIES.,Frozen Fruit & Fruit Juice Concentrates BLUEBE...
59,"ORGANIC PEARS, ORGANIC PEACHES, ORGANIC PUMPKI...","Fruit & Vegetable Juice, Nectars & Fruit Drink..."

In [71]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(rec_features['combined_features'])

In [72]:
X.shape

(39194, 6147)

In [73]:
rec_pca = PCA(500, svd_solver='arpack')
X = rec_pca.fit_transform(X)

In [74]:
X.shape

(39194, 500)

In [75]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_sim = cosine_similarity(X, X)

In [80]:
X

array([[-3.84846158e-01,  6.76849839e+00, -3.46987765e+00, ...,
         6.51474424e-02,  1.04432032e-02,  3.58117422e-02],
       [-2.92967263e+00, -6.68246906e-01, -1.02848008e-03, ...,
        -1.62569108e-01, -3.95294064e-02, -4.95265227e-02],
       [-4.52244228e+00, -1.72355016e-01, -1.01003082e+00, ...,
         4.80881700e-02,  6.23143179e-02, -9.41557543e-02],
       ...,
       [-4.17569655e+00,  1.79258366e+00, -1.75007124e+00, ...,
         2.83871568e-02, -6.00434976e-03,  2.67446806e-02],
       [-3.83578228e+00, -2.62549909e-01, -1.29631135e+00, ...,
        -7.58395204e-02, -3.91682735e-02,  3.34230819e-02],
       [ 2.17227641e+01, -5.84965798e+00,  7.85130473e-01, ...,
         5.04867162e-02, -4.09436545e-02,  2.61908264e-02]])

In [81]:
cosine_sim

array([[ 1.        ,  0.04777948,  0.05161067, ...,  0.3353724 ,
         0.20173898, -0.22202647],
       [ 0.04777948,  1.        ,  0.25914358, ...,  0.16812687,
         0.253256  , -0.36272518],
       [ 0.05161067,  0.25914358,  1.        , ...,  0.52580534,
         0.31614657, -0.41770216],
       ...,
       [ 0.3353724 ,  0.16812687,  0.52580534, ...,  1.        ,
         0.42265393, -0.47146758],
       [ 0.20173898,  0.253256  ,  0.31614657, ...,  0.42265393,
         1.        , -0.39710984],
       [-0.22202647, -0.36272518, -0.41770216, ..., -0.47146758,
        -0.39710984,  1.        ]])

In [82]:
sorted(list(enumerate(cosine_sim[0])),key=lambda x:x[1],reverse=True)

[(0, 0.9999999999999982),
 (36840, 0.9957350807487706),
 (33350, 0.9144657335872205),
 (21486, 0.8994614802585168),
 (6141, 0.8970020796261254),
 (19571, 0.8970020796261254),
 (11615, 0.8912160932895572),
 (32791, 0.8837050766276839),
 (11277, 0.8767269218994099),
 (21962, 0.8706837920523506),
 (11542, 0.866049085667175),
 (9289, 0.8607536455144164),
 (32917, 0.8598225408805953),
 (29195, 0.8422614020656315),
 (37472, 0.8413784837814163),
 (32502, 0.840024721873108),
 (18017, 0.8375672077510773),
 (19458, 0.8366329889239683),
 (6103, 0.8362640271118792),
 (35303, 0.8339363523604679),
 (3438, 0.8331475869458207),
 (21193, 0.8326349998999587),
 (1135, 0.8295459091852522),
 (32708, 0.8278732832679941),
 (16523, 0.82436183161281),
 (30213, 0.8242428458116),
 (38974, 0.8242428458116),
 (909, 0.82400156561981),
 (9137, 0.8235687458687292),
 (20320, 0.8204331821284054),
 (26927, 0.8203301265335516),
 (31225, 0.8198579259081841),
 (21829, 0.8196986620800709),
 (9126, 0.8183264505421326),
 (32916, 0.81777336612845),
 (30197, 0.8171759848772143),
 (2063, 0.8150742540948659),
 (8724, 0.8141416101339203),
 (9286, 0.8126124285190891),
 (15640, 0.8119721901797998),
 (574, 0.8116214082559893),
 (32171, 0.8084863139629996),
 (27274, 0.8082570675284513),
 (8232, 0.8081983872782174),
 (13540, 0.8081973300021884),
 (13677, 0.8069066855559015),
 (10248, 0.8057395389048827),
 (9288, 0.8056430328082259),
 (38025, 0.8056291986341192),
 (10980, 0.8053477565671369),
 (20557, 0.8051520439315116),
 (6101, 0.8033722553115651),
 (3082, 0.8018458726714024),
 (36194, 0.8018098533167918),
 (37963, 0.799844190005724),
 (35328, 0.7992151790151979),
 (36241, 0.7985715161357572),
 (11100, 0.7985495636424959),
 (8332, 0.7982098503242482),
 (3439, 0.7934190863421832),
 (19180, 0.7925307285969498),
 (18609, 0.7925007212904494),
 (36683, 0.7913977116289136),
 (17, 0.7909838041530187),
 (11494, 0.7909014749137881),
 (18402, 0.7905023234120688),
 (37274, 0.7902696007518086),
 (10979, 0.789685778671389),
 (976, 0.7893215924609719),
 (15435, 0.7892754794128733),
 (31352, 0.7883993531621792),
 (30022, 0.7868002775854634),
 (18371, 0.7858111160157984),
 (14298, 0.7853754047141812),
 (17193, 0.7845307856772582),
 (17197, 0.78275096811152),
 (6117, 0.78136455959689),
 (27916, 0.7804497135914598),
 (4915, 0.779042536913769),
 (18228, 0.7721663511099061),
 (20992, 0.7702274221323916),
 (27674, 0.7699486379378288),
 (10308, 0.7684905902788818),
 (19431, 0.7679093017432351),
 (21237, 0.7659703497980178),
 (9129, 0.7645605379141596),
 (11595, 0.7627007279680308),
 (2443, 0.7623162021964813),
 (9302, 0.761653693785163),
 (6138, 0.7581806058579794),
 (11181, 0.7537659897732196),
 (31242, 0.753031737219031),
 (12910, 0.7523402139154828),
 (36163, 0.7507057861289648),
 (36841, 0.7493633825592521),
 (37964, 0.7480902663895141),
 (2054, 0.7477475392858358),
 (35403, 0.744279414871768),
 (21485, 0.7413641810939757),
 (8689, 0.741310256314481),
 (23611, 0.7343873261376184),
 (17673, 0.733186504085395),
 (32843, 0.7309061811448877),
 (11535, 0.7293738977148382),
 (17134, 0.7292189734757443),
 (13421, 0.7291825104399805),
 (11594, 0.7281440430961652),
 (30681, 0.7267035471003372),
 (11271, 0.7250112853516356),
 (17206, 0.7247357311107089),
 (39111, 0.7231710594916837),
 (38975, 0.722909687915843),
 (30195, 0.7203944147815633),
 (39113, 0.7184529644211943),
 (37522, 0.7180714010763508),
 (28886, 0.7150249263748709),
 (1250, 0.7144439576098047),
 (8888, 0.7131575163010907),
 (4, 0.7124250414660566),
 (17946, 0.7099799989276073),
 (13425, 0.7092548933418003),
 (33002, 0.7090239459574277),
 (30825, 0.7084861644705874),
 (18368, 0.7035534596332508),
 (37623, 0.7025653978395346),
 (2442, 0.70205172651384),
 (37619, 0.7016907703622159),
 (35851, 0.700166991947769),
 (27354, 0.699164559558272),
 (8678, 0.6991244382682673),
 (25420, 0.6988984329379994),
 (37621, 0.6988905651897395),
 (22012, 0.6986217614613822),
 (27203, 0.6981896737374541),
 (36834, 0.6965881388227799),
 (36696, 0.6964819819484798),
 (7817, 0.6963902193464214),
 (7013, 0.6957600067385217),
 (7614, 0.694910685361814),
 (19570, 0.6941811737143009),
 (33259, 0.6937928504955236),
 (32990, 0.693720618143991),
 (18379, 0.6930206398045708),
 (20051, 0.6915345633152108),
 (31279, 0.690965080226699),
 (21698, 0.6894132153375582),
 (13669, 0.6886845041473891),
 (29341, 0.6883230998197605),
 (1083, 0.6881442082398578),
 (17932, 0.6875091139316397),
 (36600, 0.6869790848092293),
 (10981, 0.6869604144869416),
 (34930, 0.686892883803327),
 (31277, 0.6855769184788694),
 (7024, 0.6853910793648225),
 (13895, 0.6849174382367471),
 (7297, 0.6845573827719094),
 (30550, 0.6838611459703204),
 (11957, 0.6835201383911643),
 (1472, 0.6832668823698272),
 (7134, 0.6831836003533021),
 (7920, 0.68187991335199),
 (39110, 0.6810961198202579),
 (32736, 0.6806789733855502),
 (35814, 0.6806789733855502),
 (17820, 0.6805694565833162),
 (7008, 0.6798927048282108),
 (11620, 0.6792053401088033),
 (7507, 0.678669570822169),
 (36601, 0.6782731980739226),
 (34087, 0.6775434631131892),
 (2454, 0.6773876740065987),
 (6683, 0.6772945355092438),
 (17743, 0.6764448582633401),
 (7298, 0.6753682157885083),
 (36555, 0.6753676318443781),
 (13349, 0.6752475211137218),
 (24145, 0.6751697809801873),
 (36606, 0.6747264759740602),
 (19089, 0.6738698381050289),
 (10827, 0.6733504528337463),
 (10169, 0.6722764457990577),
 (39112, 0.6718575318449569),
 (16686, 0.6716051238768009),
 (36604, 0.6715468671844992),
 (5345, 0.6714153780558626),
 (2427, 0.6710691283934681),
 (21697, 0.6707065599773333),
 (7021, 0.6704315982046459),
 (20781, 0.6702499152272721),
 (31199, 0.6699388112166759),
 (31278, 0.6698872110490902),
 (323, 0.669377759531934),
 (7633, 0.669154788199995),
 (7635, 0.6685153881829228),
 (32113, 0.6682800569832719),
 (37962, 0.6674518065682936),
 (32114, 0.6673662116119006),
 (30322, 0.6657191394475753),
 (6139, 0.6650381920642865),
 (9123, 0.6650381920642865),
 (2615, 0.664546373091426),
 (36830, 0.6642640170246198),
 (8335, 0.664003203889505),
 (13645, 0.6638642715629846),
 (6814, 0.6637569120821412),
 (6527, 0.6632300557752027),
 (32112, 0.6631406936498073),
 (28091, 0.6630064370717224),
 (35500, 0.6628437387258761),
 (4707, 0.662818575778123),
 (24931, 0.6625834028325989),
 (26048, 0.6625731061396476),
 (1559, 0.6621697930721469),
 (38870, 0.6620458698647449),
 (33225, 0.661981579688535),
 (36844, 0.661066958187722),
 (13672, 0.6607498010468648),
 (33849, 0.6607486740881094),
 (31655, 0.6606216968957984),
 (27872, 0.6605402404109997),
 (27871, 0.6600209207409272),
 (7634, 0.6599014652321916),
 (16949, 0.6596115257699419),
 (8490, 0.6595632362935452),
 (29049, 0.6594189668365068),
 (7663, 0.6592417582371333),
 (31650, 0.6591765105742563),
 (2325, 0.6587479279954586),
 (32096, 0.6584299608389093),
 (32097, 0.6583561470216078),
 (7625, 0.6577667512367944),
 (29046, 0.6573817718001794),
 (11533, 0.6572028364743929),
 (21699, 0.6561795797334953),
 (29048, 0.6560741534223291),
 (33207, 0.6558562470394546),
 (38871, 0.6557763932047267),
 (16181, 0.6556353003657046),
 (11598, 0.6555444018500506),
 (1560, 0.6555227642340264),
 (23185, 0.6552196207519434),
 (33847, 0.6549073057911988),
 (27870, 0.6548796540567023),
 (19699, 0.6548404623835427),
 (31652, 0.6545121833058077),
 (29047, 0.6542856176647961),
 (14687, 0.6541028721726012),
 (10844, 0.654041626282695),
 (4703, 0.6538404805163832),
 (17953, 0.6536653489464166),
 (2461, 0.653579267068741),
 (10148, 0.6533055461784676),
 (5723, 0.6532314068567632),
 (10162, 0.6529097397235353),
 (6249, 0.6526884571899744),
 (4807, 0.6525858768945813),
 (1473, 0.6525125059161604),
 (33837, 0.6522180967702967),
 (18874, 0.6522174127626879),
 (14847, 0.6519758944711406),
 (29268, 0.6518392754411756),
 (35427, 0.6515928295121836),
 (36736, 0.6513993688224046),
 (4803, 0.6509744137282795),
 (27868, 0.6506325248104975),
 (27869, 0.6505570742296898),
 (9823, 0.6503402567203166),
 (37469, 0.6502210255213329),
 (9826, 0.6501357313941664),
 (4811, 0.6500846289748641),
 (7025, 0.6496299934833945),
 (27911, 0.6494816240549385),
 (8735, 0.6487368393718346),
 (3242, 0.64867541451747),
 (37203, 0.6485842715840571),
 (4626, 0.6485759491736456),
 (4808, 0.6484914301371888),
 (10167, 0.6484093650422557),
 (2666, 0.6479443628903471),
 (14688, 0.6478379147294989),
 (5479, 0.6476988939546223),
 (5974, 0.6476174487258319),
 (18782, 0.6475058203841783),
 (30556, 0.6474650811022554),
 (10229, 0.6473326336079277),
 (18873, 0.6471807758918298),
 (7020, 0.647174425913906),
 (39185, 0.6469948097982724),
 (2052, 0.6469702118216564),
 (35360, 0.6464725847758502),
 (21467, 0.6456701817340752),
 (907, 0.6455970524860304),
 (32912, 0.6455157414829849),
 (18871, 0.6453978249720401),
 (13676, 0.6448004011952321),
 (908, 0.6447976454986936),
 (3241, 0.6447883276673525),
 (21234, 0.6443033281133478),
 (36465, 0.6439989393664728),
 (33724, 0.643933503285241),
 (31446, 0.6436367977072112),
 (18383, 0.6431450852499614),
 (28789, 0.6430054076606049),
 (8669, 0.6425492360358821),
 (33250, 0.6424489364228128),
 (8580, 0.6423847163520624),
 (36383, 0.6423418089347461),
 (33321, 0.6420751466361789),
 (8668, 0.6419998366617538),
 (20616, 0.6418202611232283),
 (17188, 0.6417329055085236),
 (651, 0.6415796428244748),
 (29000, 0.6415125891209834),
 (18697, 0.6414618097713713),
 (18698, 0.6414005875354636),
 (30323, 0.6412925198292151),
 (39095, 0.6412897745446857),
 (36892, 0.6410832018232515),
 (35804, 0.64108310782713),
 (981, 0.6407754387487871),
 (21979, 0.6407142017083973),
 (36167, 0.6405261505795115),
 (16141, 0.6405023125677911),
 (6170, 0.6404824336174334),
 (31514, 0.6402219023252567),
 (11534, 0.6400918735254671),
 (34097, 0.6400533292933235),
 (10787, 0.6398840031723649),
 (36679, 0.639845166284596),
 (30198, 0.6397168747757715),
 (36571, 0.639667844706394),
 (7128, 0.6396590833105265),
 (18859, 0.6389504859256792),
 (34645, 0.6389322049787384),
 (8649, 0.6388308484202497),
 (14533, 0.6387175660188026),
 (28981, 0.6386494260647507),
 (31355, 0.6382330982738333),
 (35971, 0.6381773944178725),
 (13833, 0.6380010577067741),
 (3441, 0.6379640596015128),
 (4121, 0.6377834843668493),
 (9300, 0.6377708242494433),
 (10230, 0.6377478258975664),
 (11619, 0.6374901462289876),
 (32224, 0.636950314620906),
 (17493, 0.63678732541247),
 (2145, 0.6367288073336618),
 (36184, 0.6364861714468493),
 (8578, 0.6363738036824368),
 (32317, 0.6359997242743851),
 (31656, 0.6354906447555412),
 (12214, 0.6354813394857783),
 (13559, 0.6352306504833586),
 (8528, 0.6351584739552815),
 (30257, 0.6349918782714543),
 (31651, 0.6348299508704707),
 (18903, 0.6348026323648102),
 (10163, 0.6346157224050577),
 (28187, 0.6343817467658847),
 (17866, 0.6338295393585577),
 (2619, 0.6337536363502733),
 (11519, 0.6337533647111036),
 (30846, 0.6336195463513576),
 (32245, 0.6333865044812743),
 (10864, 0.633129177761071),
 (29034, 0.6331190775569305),
 (20611, 0.6330397797556452),
 (36503, 0.6330344184974771),
 (4597, 0.632854513269013),
 (14023, 0.632854513269013),
 (21701, 0.632831650824598),
 (28132, 0.6327519618052608),
 (12952, 0.6326647171898675),
 (12974, 0.6325284884903882),
 (5476, 0.6324469346750368),
 (32247, 0.6323951546453589),
 (15149, 0.632366538926441),
 (32519, 0.632239443128677),
 (8695, 0.6320955316533073),
 (27517, 0.63205344399062),
 (36554, 0.632017867328161),
 (16189, 0.6318719845417395),
 (482, 0.6317068548151334),
 (11396, 0.6316388220509569),
 (30011, 0.6312856981105717),
 (18008, 0.6311592754341606),
 (12998, 0.6311470197831365),
 (8206, 0.6310847327704997),
 (9268, 0.6310581729627569),
 (32168, 0.6308056483326245),
 (28020, 0.6307955598507887),
 (37603, 0.6306510286147585),
 (8666, 0.6306312490610255),
 (9985, 0.6305700013020099),
 (9987, 0.6305700013020099),
 (36521, 0.630453152864),
 (32771, 0.630132400241747),
 (6337, 0.6301217124476605),
 (7014, 0.6301101022478318),
 (32584, 0.6298438850623458),
 (14487, 0.6298093913397886),
 (34271, 0.6298043202139505),
 (33484, 0.6297740196565842),
 (27534, 0.6295262306306709),
 (36943, 0.6295104066682266),
 (2160, 0.629492609415312),
 (27940, 0.6294268437422763),
 (31101, 0.6292168571672),
 (32243, 0.629020025489302),
 (31817, 0.6289697491068473),
 (1134, 0.6289655902592892),
 (28222, 0.6289568150194487),
 (11866, 0.6286449896165687),
 (10168, 0.6285663153013402),
 (1770, 0.6285040730660538),
 (18768, 0.6284160795617899),
 (2441, 0.6282994166576036),
 (28021, 0.6281296478048811),
 (12101, 0.6280500342649228),
 (14314, 0.6279862135326003),
 (16932, 0.6279678098831456),
 (12953, 0.6279632546731533),
 (34263, 0.6279526430282484),
 (30355, 0.6278688146680562),
 (16549, 0.6274461325597516),
 (30904, 0.6272842670753745),
 (5462, 0.627255127049066),
 (31294, 0.6271598982037798),
 (10164, 0.6271176466576854),
 (36308, 0.6270808661755402),
 (21638, 0.6270791185303474),
 (7131, 0.626991414585325),
 (9483, 0.6267688958664382),
 (35096, 0.6263750191137722),
 (21641, 0.6260914760085905),
 (29405, 0.6260037302233219),
 (30504, 0.6259013751945991),
 (9798, 0.6257636531374755),
 (29494, 0.6257130503745746),
 (8824, 0.6252128517866747),
 (12058, 0.6252016253455692),
 (31723, 0.6250214443035123),
 (2159, 0.6249104710033478),
 (17496, 0.6248817550902337),
 (35920, 0.6248112274903521),
 (36637, 0.6246115301083952),
 (2055, 0.6243005403048418),
 (7914, 0.6241218151278695),
 (15798, 0.6240688812933943),
 (39023, 0.6240346786123363),
 (32244, 0.6237830237920763),
 (37593, 0.6237403238712643),
 (16769, 0.6233984297798643),
 (37553, 0.6233036697634506),
 (1075, 0.6231441698218861),
 (13353, 0.6229505047158113),
 (25596, 0.6227541429564684),
 (8696, 0.6226683745963758),
 (28185, 0.6225945026960279),
 (26451, 0.62255021940528),
 (21635, 0.6224714472273936),
 (5, 0.6223746566194494),
 (27273, 0.6220397683408563),
 (32248, 0.6218267601490406),
 (26453, 0.6217468607967057),
 (8721, 0.6217343766629044),
 (38082, 0.6216255439681025),
 (5722, 0.6216083943112446),
 (11601, 0.6214898572247048),
 (19892, 0.6214831161518345),
 (19943, 0.6212403375226668),
 (16623, 0.6212310782205036),
 (31014, 0.6211893126347322),
 (6328, 0.6211802344760057),
 (6127, 0.62116200543988),
 (8723, 0.62116200543988),
 (37449, 0.6211482593525052),
 (1588, 0.6208331926031108),
 (31263, 0.620727282769273),
 (8333, 0.6207098325098265),
 (19820, 0.6205159171280692),
 (15490, 0.6203760556708111),
 (17033, 0.6203590731193103),
 (36557, 0.620353213098894),
 (17025, 0.620268809191459),
 (3442, 0.6198907584280523),
 (33717, 0.6198462434931546),
 (7268, 0.6195958861440032),
 (17034, 0.6194310229188904),
 (27547, 0.619381432518542),
 (25077, 0.6193005713233054),
 (32770, 0.6190459657551493),
 (34753, 0.6189190103601278),
 (11097, 0.6187898038100187),
 (1882, 0.6186737644134866),
 (19773, 0.6186451460398413),
 (6484, 0.6185939313021388),
 (703, 0.6185684085436616),
 (27995, 0.6179068814900843),
 (32242, 0.6178842395510691),
 (34009, 0.6178612181475557),
 (2595, 0.6175498307385886),
 (32418, 0.6173625662132998),
 (1852, 0.617296970768058),
 (21637, 0.6168992469260394),
 (36891, 0.6166890746147909),
 (33438, 0.6165662814329798),
 (36854, 0.6161732743390425),
 (12395, 0.6161267676189526),
 (35072, 0.6160996281945511),
 (38839, 0.6160996281945511),
 (13426, 0.6160930343821706),
 (34763, 0.6160458662204622),
 (37491, 0.6160375355047059),
 (1203, 0.6157881804483483),
 (21205, 0.6155460152252588),
 (34806, 0.6155070133937595),
 (28475, 0.6154262985699704),
 (29907, 0.6153271173530865),
 (9491, 0.6151312968421534),
 (37552, 0.6148579344962303),
 (10845, 0.6148312223484445),
 (21642, 0.6147209668316527),
 (36735, 0.6146186080482371),
 (37131, 0.6145276522997478),
 (8693, 0.6145031836672038),
 (10037, 0.6144960507634275),
 (2522, 0.6144039113234652),
 (37551, 0.6143765613305868),
 (19945, 0.6142964214248933),
 (28133, 0.6142246176847792),
 (2132, 0.6141586741010229),
 (20821, 0.6140113812351213),
 (31518, 0.6139721993279634),
 (17131, 0.6139545254349319),
 (6566, 0.6138692941564284),
 (8722, 0.6138247491042776),
 (19251, 0.6137798383786441),
 (8231, 0.6135056978931538),
 (30930, 0.6135048272141339),
 (20373, 0.6134576735895966),
 (5967, 0.6131107032994525),
 (985, 0.6130557227249978),
 (5296, 0.613025437007288),
 (19733, 0.6129392456914015),
 (31752, 0.6128181175556339),
 (23749, 0.6126367592801328),
 (14539, 0.6125751080332463),
 (32413, 0.6125006704692246),
 (6552, 0.6122964730226725),
 (21291, 0.6121442817069952),
 (20216, 0.6120640666406684),
 (31702, 0.6119827808358536),
 (21412, 0.6119777344721514),
 (28131, 0.6118449956055776),
 (16180, 0.6117993505781348),
 (36791, 0.6113775235803782),
 (8345, 0.6110870849144371),
 (5473, 0.611081889919384),
 (21634, 0.6107723654457778),
 (36685, 0.6106878278243693),
 (2458, 0.6105498997182258),
 (20738, 0.6102884409018215),
 (7816, 0.6102747700424833),
 (37279, 0.610203231592644),
 (8700, 0.6099476582823805),
 (19732, 0.6099268630921695),
 (16364, 0.6099134955230558),
 (16632, 0.609576434231989),
 (19898, 0.6094199201160938),
 (8641, 0.6094036276179804),
 (32414, 0.6093432419553265),
 (18071, 0.6092947443078731),
 (32679, 0.6090526493235602),
 (17674, 0.6088589244528181),
 (27861, 0.6087826759859566),
 (11439, 0.6087785219993371),
 (33404, 0.6087376944025797),
 (18945, 0.6086507229329193),
 (6567, 0.6086042947052476),
 (7232, 0.6086042947052476),
 (33424, 0.6085619312116425),
 (7148, 0.6085288080090565),
 (34008, 0.6085094999335858),
 (11004, 0.6084412474721976),
 (15243, 0.6084099795729745),
 (37471, 0.6082506861587407),
 (36877, 0.6080562322155812),
 (29497, 0.6080302968899962),
 (27553, 0.6078935659561109),
 (3425, 0.6076755264485592),
 (28904, 0.6076218462377215),
 (27899, 0.6073816100221414),
 (32914, 0.6073449572515467),
 (905, 0.6072414430428194),
 (28097, 0.6072374228463977),
 (20547, 0.6072192384425565),
 (26535, 0.6071770212797558),
 (7915, 0.6071256890254938),
 (4770, 0.6070867516332116),
 (20649, 0.6070803699809774),
 (30958, 0.6070774697224145),
 (31266, 0.6070442608646798),
 (25845, 0.6069245450201091),
 (17551, 0.6067589603716083),
 (2102, 0.6067122585725057),
 (7859, 0.6066417555297812),
 (21481, 0.6066243485283049),
 (12014, 0.6065504860024706),
 (26984, 0.606484571492665),
 (34236, 0.6064158118025649),
 (29276, 0.6063617480376349),
 (27618, 0.6056593506303568),
 (37677, 0.6055324655039237),
 (31246, 0.6054362452906695),
 (6549, 0.6053780353237673),
 (10331, 0.6052647930958847),
 (37678, 0.6052568917459619),
 (28141, 0.6052224056623766),
 (8350, 0.6052180019668337),
 (29595, 0.6051905424295517),
 (20017, 0.6051551141659306),
 (14532, 0.6051271576332117),
 (575, 0.6050784498245781),
 (11609, 0.6050784498245781),
 (27250, 0.6050166024045678),
 (13948, 0.6048767798313558),
 (8331, 0.6048336113422274),
 (35187, 0.6047838505769001),
 (2593, 0.6047795101771043),
 (18408, 0.6047795101771043),
 (36385, 0.6043370132462331),
 (13779, 0.6041278757743419),
 (32169, 0.6041127575284798),
 (30021, 0.6040396170448086),
 (38883, 0.6039498499381734),
 (15641, 0.6037727438347285),
 (483, 0.6037727438347281),
 (31644, 0.6036565232815356),
 (30744, 0.6035754535378166),
 (9675, 0.603496426008726),
 (28134, 0.6033608897771803),
 (7643, 0.60312821225202),
 (8003, 0.60312821225202),
 (9248, 0.6031068214128532),
 (38743, 0.6030006584885508),
 (32923, 0.6029739124391251),
 (8636, 0.6028770617747612),
 (9119, 0.6027933013284534),
 (10829, 0.6026972848854871),
 (32078, 0.6025575839491347),
 (283, 0.6023056442854966),
 (7868, 0.6019799779378374),
 (31497, 0.6018515086545275),
 (37550, 0.6016678510492602),
 (906, 0.6013318056098541),
 (23264, 0.6007679856564236),
 (21288, 0.6007343331336453),
 (31326, 0.6004972507951002),
 (8642, 0.600365295263787),
 (8535, 0.6003434482581548),
 (7127, 0.6002654619228802),
 (14542, 0.6002389279929493),
 (31498, 0.6001308171840114),
 (5388, 0.6001172674217816),
 (321, 0.6000118493281454),
 (22301, 0.6000112346274038),
 (13627, 0.599892350902093),
 (22305, 0.5998891737553952),
 (1102, 0.5993425352194138),
 (17533, 0.5993396821807861),
 (10443, 0.5993095629637751),
 (9058, 0.5992305770490671),
 (30746, 0.5992148276457013),
 (31492, 0.5992121545058663),

In [102]:
rec_features = rec_features.reset_index()

In [103]:
rec_features[rec_features.ingredients == "ORGANIC GREEN PEAS"].index[0]

6104

In [108]:
rec_features.iloc[1:6]

,index,ingredients,combined_features
1,15,"PINEAPPLE, WATER, SUGAR, AND CITRIC ACID.","Canned Fruit PINEAPPLE, WATER, SUGAR, AND CITR..."
2,30,"SUGAR SNAP PEAS, CARROTS, ONIONS, MUSHROOMS.","Frozen Vegetables SUGAR SNAP PEAS, CARROTS, ON..."
3,44,BLUEBERRIES.,Frozen Fruit & Fruit Juice Concentrates BLUEBE...
4,59,"ORGANIC PEARS, ORGANIC PEACHES, ORGANIC PUMPKI...","Fruit & Vegetable Juice, Nectars & Fruit Drink..."
5,76,"ORGANIC BUTTER LETTUCES, ORGANIC OAK LEAF, ORG...",Pre-Packaged Fruit & Vegetables ORGANIC BUTTER...

In [ ]:
rec_features

In [133]:
def recommend(title):
    index = rec_features[rec_features.ingredients == title].index[0]
    distances=sorted(list(enumerate(cosine_sim[index])),key=lambda x:x[1],reverse=True)
    for i in distances[1:10]:
        print(rec_features.iloc[i[0]].ingredients)

In [135]:
title = 'ORGANIC GREEN PEAS'
recommendations = recommend(title)

if recommendations is not None:
    print(recommendations)

ORGANIC GREEN PEAS.
ORGANIC GREEN PEAS
GREEN PEAS.
GREEN PEAS.
PETITE GREEN PEAS.
GREEN PEAS.
ORGANIC GREEN PEAS.
ORGANIC GREEN PEAS.
ORGANIC PEAS.